# zinit
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
if [[ ! -d "$ZINIT_HOME" ]]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

# plugins (turbo mode - loaded after prompt)
zinit light-mode wait lucid for \
  zsh-users/zsh-autosuggestions \
  zsh-users/zsh-syntax-highlighting

# completions (cached, no compaudit)
autoload -Uz compinit
if [[ -f "${ZDOTDIR:-$HOME}/.zcompdump" && $(date +'%j') == $(stat -f '%Sm' -t '%j' "${ZDOTDIR:-$HOME}/.zcompdump" 2>/dev/null) ]]; then
  compinit -C
else
  compinit
fi

fpath=($HOME/.config/zsh/completions $fpath)

# Use rg to respect .gitignore
export FZF_DEFAULT_COMMAND='rg --hidden --ignore .git -g ""'

source $HOME/.config/zsh/aliases.zsh
source $HOME/.config/zsh/path.zsh
source $HOME/.config/zsh/includes.zsh

eval "$(starship init zsh)"

export EDITOR="nvim"
export PATH="$HOME/.local/bin:$PATH"
