devbox_tools:
  - prettyping@latest
  - bat@latest
  - htop@latest
  - fzf@latest
  - delta@latest
  - tealdeer@latest
  - ripgrep@latest
  - lazydocker@latest
  - entr@latest

homebrew_tools:
  - gnu-sed
  - lastpass-cli
