- name: Set up local workstation
  hosts: local
  roles:
    # ====================
    #   Tools
    # ====================
    - role: config
      tags:
        - config
    - role: homebrew
      tags:
        - homebrew
    - role: git
      tags:
        - git
    - role: asdf
      tags:
        - asdf
    - role: cli
      tags:
        - cli
    - role: zsh
      tags:
        - zsh
    - role: tmux
      tags:
        - tmux
    - role: pgcli
      tags:
        - pgcli
    - role: mcp-hub
      tags:
        - mcp-hub
    - role: neovim
      tags:
        - neovim


    # ====================
    #   Apps
    # ====================
    - role: aerospace
      tags:
        - aerospace
    - role: browsers
      tags:
        - browsers
    - role: kitty
      tags:
        - kitty
    - role: ghostty
      tags:
        - ghostty


    # ====================
    #   Languages
    # ====================
    - role: ruby
      tags:
        - ruby
    - role: JavaScript
      tags:
        - javascript


    # ====================
    #   Desktop
    # ====================
    - role: sketchybar
      tags:
        - sketchybar


    # ====================
    #   System
    # ====================
    - role: macos
      tags:
        - macos
