- name: Set up local workstation
  hosts: local
  roles:
    # ====================
    #   Tools
    # ====================
    - role: config
      tags:
        - config
    - role: homebrew
      tags:
        - homebrew
    - role: git
      tags:
        - git
    - role: asdf
      tags:
        - asdf
    - role: cli
      tags:
        - cli
    - role: zsh
      tags:
        - zsh
    - role: tmux
      tags:
        - tmux
    - role: pgcli
      tags:
        - pgcli
    - role: mycli
      tags:
        - mycli
    - role: claude
      tags:
        - claude
    - role: neovim
      tags:
        - neovim
    - role: helix
      tags:
        - helix
    - role: zellij
      tags:
        - zellij

    # ====================
    #   Apps
    # ====================
    - role: aerospace
      tags:
        - aerospace
    - role: browsers
      tags:
        - browsers
    - role: kitty
      tags:
        - kitty
    - role: ghostty
      tags:
        - ghostty
    - role: sol
      tags:
        - sol

    # ====================
    #   Languages
    # ====================
    - role: ruby
      tags:
        - ruby
    - role: JavaScript
      tags:
        - javascript

    # ====================
    #   Desktop
    # ====================
    - role: sketchybar
      tags:
        - sketchybar

    # ====================
    #   System
    # ====================
    - role: karabiner
      tags:
        - karabiner
    - role: macos
      tags:
        - macos
