- name: Set up local workstation
  hosts: local
  roles:
    # ====================
    #   Tools
    # ====================
    - role: config
      tags:
        - config
    - role: homebrew
      tags:
        - homebrew
    - role: git
      tags:
        - git
      dependencies:
        - homebrew
    - role: asdf
      tags:
        - asdf
      dependencies:
        - role: homebrew
    - role: cli
      tags:
        - cli
      dependencies:
        - role: homebrew
    - role: zsh
      tags:
        - zsh
      dependencies:
        - role: homebrew
        - role: cli
        - role: git


    # ====================
    #   Apps
    # ====================
    - role: browsers
      tags:
        - browsers
      dependencies:
        - role: homebrew
    - role: kitty
      tags:
        - kitty
      dependencies:
        - role: config
        - role: homebrew


    # ====================
    #   Languages
    # ====================
    - role: ruby
      tags:
        - ruby
      dependencies:
        - role: asdf
    - role: JavaScript
      tags:
        - javascript
      dependencies:
        - role: asdf
