- name: Set up local workstation
  hosts: local
  roles:
    - role: homebrew
      tags:
        - homebrew
    - role: browsers
      tags:
        - browsers
    - role: git
      tags:
        - git
