- name: Ensure mcp-hub is installed
  npm:
    name: mcp-hub
    global: yes

- name: Check if mcp-hub config directory exists
  stat:
    path: "{{ config }}/mcp-hub"
  register: mcp_hub_dir

- name: Copy mcp-hub configuration files
  copy:
    src: "{{ dotfiles_home }}/roles/mcp-hub/files/"
    dest: "{{ config }}/mcp-hub"
  when: not mcp_hub_dir.stat.exists
