- name: Install Spotify
  homebrew_cask:
    name: spotify

- name: Install Spicetify
  homebrew:
    name: khanhas/tap/spicetify-cli

- name: Update Spicetify
  command: spicetify update

# Theme installation
- name: Clone Spicetify themes
  command: git clone --depth=1 https://github.com/spicetify/spicetify-themes.git ~/tmp/spicetify-themes
  args:
    creates: ~/tmp/spicetify-themes

- name: Ensure Spicetify themes directory exists
  command: mkdir -p {{ config }}/spicetify/Themes
  args:
    creates: "{{ config }}/spicetify/Themes"

- name: Copy Spicetify themes to config directory
  command: cp -r ~/tmp/spicetify-themes/ {{ config }}/spicetify/Themes
  args:
    creates: "{{ config }}/spicetify/Themes/text"

- name: Delete tmp directory
  command: rm -rf ~/tmp/spicetify-themes

# Configure Extensions
- name: Keyboard Shortcuts
  command: spicetify config extensions keyboardShortcut.js

- name: Full App Display
  command: spicetify config extensions fullAppDisplay.js

- name: Bookmark
  command: spicetify config extensions bookmark.js

# Configure Theme
- name: Set current theme to 'text'
  command: spicetify config current_theme text

- name: Set theme color scheme to 'RosePineMoon'
  command: spicetify config color_scheme RosePineMoon

- name: Ensure install is happening from a clean state
  command: spicetify restore
  ignore_errors: True

- name: Delete old backup and return to default state
  command: spicetify clear

- name: Create a backup and apply config
  command: spicetify backup apply
