DesktopScreenSaver_BackGroundImage: "{{ role_path }}/files/wallpaper.jpg"           # Background image
DesktopScreenSaver_askForPassword: yes           # Require password after sleep or screen saver begins
DesktopScreenSaver_askForPasswordDelay: 0        # Require password immediately
