# ====================
#   Prefix
# ====================
unbind C-b
set-option -g prefix `
bind ` send-prefix

# ====================
#   General
# ====================
setw -g aggressive-resize on
set -g mouse on
setw -g mode-keys vi
set -g renumber-windows on
set -sg escape-time 0
set -g history-limit 10000
set-option -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g monitor-bell on
set -g bell-action other

# ====================
#   Colors / Terminal
# ====================
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-ghostty:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
set-option -g focus-events on

# ====================
#   Status Bar Theme
# ====================
# Layout/format live in layout.conf; this is for elements not styled there.
set -g message-style "bg=default,fg=#5ea1ff"
set -g message-command-style "bg=default,fg=#5ea1ff"
set -g window-status-activity-style "bg=default,fg=#f1ff5e"

# ====================
#   Reload
# ====================
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"
